config/routes.rb
Rutas::Application.routes.draw do
  resources :bus_entries
  resources :fares
  resources :bus_entry_vouchers
  resources :vouchers
  resources :shifts
  resources :periods
  resources :operators
  resources :units
  resources :partners
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup

  root :to => 'users#new'

end

app/models/bus_entry.rb
class BusEntry < ActiveRecord::Base
  attr_accessible :adult_tickets, :average_income, :average_time, :current_adult_fare, :current_feria_fare, :current_preferent_fare, :diesel_liters, :diesel_price, :extra_hours, :feria_tickets, :feria_total_income, :laps, :operator_id, :operator_salary, :other_expenses, :other_expenses_description, :preferent_tickets, :shift_id, :total_income, :total_tickets, :unit_expenses, :unit_id, :worked_hours
  belongs_to :shift
end

app/models/bus_entry_voucher.rb
class BusEntryVoucher < ActiveRecord::Base
  attr_accessible :amount, :bus_entry_id, :voucher_id
end

app/models/fare.rb
class Fare < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :address, :cellphone_number, :email, :employee_number, :first_name, :last_name, :phone_number
end

app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :units
  	attr_accessible :first_name, :last_name, :address, :phone_number, :email, :rfc
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :beginning_date, :diesel_total, :duration, :end_date, :file_name, :ledger_account, :period_number, :status, :total
  has_many :shifts
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  attr_accessible :day, :partner_earnings, :period_id, :period_id, :shift_total, :shift_type
  belongs_to :period
  has_many :bus_entries
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :number, :partner_id
  belongs_to :partner
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :name, :email, :password, :password_confirmation, :login, :crypted_password, :password_salt, :persistence_token, :single_access_token, :perishable_token, :login_count, :failed_login_count, :last_request_at, :current_login_at, :last_login_at, :current_login_ip, :last_login_ip
  acts_as_authentic do |c|
  	c.login_field = 'email'
  end # block optional
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  # GET /fares
  # GET /fares.json
  def index
    @fares = Fare.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fares }
    end
  end

  # GET /fares/1
  # GET /fares/1.json
  def show
    @fare = Fare.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/new
  # GET /fares/new.json
  def new
    @fare = Fare.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/1/edit
  def edit
    @fare = Fare.find(params[:id])
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(params[:fare])

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render json: @fare, status: :created, location: @fare }
      else
        format.html { render action: "new" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fares/1
  # PUT /fares/1.json
  def update
    @fare = Fare.find(params[:id])

    respond_to do |format|
      if @fare.update_attributes(params[:fare])
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare = Fare.find(params[:id])
    @fare.destroy

    respond_to do |format|
      format.html { redirect_to fares_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
    @period = Period.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/new
  # GET /periods/new.json
  def new
    @period = Period.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/1/edit
  def edit
    @period = Period.find(params[:id])
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(params[:period])

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render json: @period, status: :created, location: @period }
      else
        format.html { render action: "new" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /periods/1
  # PUT /periods/1.json
  def update
    @period = Period.find(params[:id])

    respond_to do |format|
      if @period.update_attributes(params[:period])
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period = Period.find(params[:id])
    @period.destroy

    respond_to do |format|
      format.html { redirect_to periods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def spanish_month(month)
  	mes = case month
  		when 1 then 'Ene'
  		when 2 then 'Feb'
  		when 3 then 'Mar'
  		when 4 then 'Abr'
  		when 5 then 'May'
  		when 6 then 'Jun'
  		when 7 then 'Jul'
  		when 8 then 'Ago'
  		when 9 then 'Sep'
  		when 10 then 'Oct'
  		when 11 then 'Nov'
  		when 12 then 'Dic'
  		else 'No es un mes'
  	end
  	mes
  end
end

app/helpers/bus_entries_helper.rb
module BusEntriesHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/periods/_form.html.erb
<%= form_for @period, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :period_number, 'Período', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :period_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :beginning_date, 'Fecha inicial', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :beginning_date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, 'Fecha final', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :end_date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :duration, 'Duración', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :duration, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, 'Estatus', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :file_name, 'Nombre de archivo', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :file_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total, 'Total', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :diesel_total, 'Diésel total', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :diesel_total, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ledger_account, 'Cuenta contable', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ledger_account, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Crear', :class => 'btn btn-default btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                periods_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1> Per&iacute;odos </h1>
</div>
<%= render :partial => 'form' %>

app/views/periods/index.html.erb
<%- model_class = Period -%>
<%
today  = Date.today
first_day = (today.wday==3) ? today : today-(today.wday-3)
%>


<div class='period'>

  <div class="row period_title">
    <div class="week_title"><h2>Semana <%=today.cweek%></h2></div>
    <div class="period_button"><button type="button" class="btn btn-primary" style="margin-top:18px;">Capturar Jornada</button></div>
  </div>

<%(first_day..(first_day+6.days)).each do |day|%>

  <div class='day'>
    <div class='day_name'><%=(Rutas::Application.config.dias[day.wday]).html_safe%></div>
    <div class='shift_1 shift_1_complete'>
      Shift 1
    </div>
    <div class='month_day'>
      <div class='month_day_text'><%=(Rutas::Application.config.meses_abr[day.mon]).html_safe%> <%=day.mday%></div>
    </div>
    <div class='shift_2 shift_2_complete'>
      Shift 2
    </div>
  </div>
<%end%>

<div class='clearfix'></div>
<br /><br /><br />

<div class="page-header">
  <h1> Per&iacute;odos </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th> N&uacute;mero de per&iacute;odo </th>
      <th> Fecha inicial </th>
      <th> Fecha final </th>
      <th> Durac&iacute;on </th>
      <th> Estatus </th>
      <th> Nombre de archivo </th>
      <th> Total </th>
      <th> Total de di&eacute;sel </th>
      <th> Cuenta contable </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= link_to period.id, period_path(period) %></td>
        <td><%= period.period_number %></td>
        <td><%= period.beginning_date %></td>
        <td><%= period.end_date %></td>
        <td><%= period.duration %></td>
        <td><%= period.status %></td>
        <td><%= period.file_name %></td>
        <td><%= period.total %></td>
        <td><%= period.diesel_total %></td>
        <td><%= period.ledger_account %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_period_path(period), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      period_path(period),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarlo permanentemente de la base de datos?')) },
                      :class => 'btn btn-default btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_period_path,
            :class => 'btn btn-default btn-primary' %>

app/views/periods/new.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1> Nuevo per&iacute;odo </h1>
</div>
<%= render :partial => 'form' %>

app/views/periods/show.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:period_number) %>:</strong></dt>
  <dd><%= @period.period_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:beginning_date) %>:</strong></dt>
  <dd><%= @period.beginning_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @period.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @period.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @period.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file_name) %>:</strong></dt>
  <dd><%= @period.file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= @period.total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diesel_total) %>:</strong></dt>
  <dd><%= @period.diesel_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ledger_account) %>:</strong></dt>
  <dd><%= @period.ledger_account %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              periods_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_period_path(@period), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              period_path(@period),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Está seguro que desea eliminarlo permanentemente de la base de datos?')) },
              :class => 'btn btn-default btn-danger' %>
</div>