config/routes.rb
Rutas::Application.routes.draw do
  resources :bus_entries
  resources :fares
  resources :bus_entry_vouchers
  resources :vouchers
  resources :shifts
  resources :periods
  resources :operators
  resources :units
  resources :partners
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup

  root :to => 'users#new'

end

app/models/bus_entry.rb
class BusEntry < ActiveRecord::Base
  attr_accessible :adult_tickets, :average_income, :average_time, :current_adult_fare, :current_feria_fare, :current_preferent_fare, :diesel_liters, :diesel_price, :extra_hours, :feria_tickets, :feria_total_income, :laps, :operator_id, :operator_salary, :other_expenses, :other_expenses_description, :preferent_tickets, :shift_id, :total_income, :total_tickets, :unit_expenses, :unit_id, :worked_hours
  belongs_to :shift
end

app/models/bus_entry_voucher.rb
class BusEntryVoucher < ActiveRecord::Base
  attr_accessible :amount, :bus_entry_id, :voucher_id
end

app/models/fare.rb
class Fare < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :address, :cellphone_number, :email, :employee_number, :first_name, :last_name, :phone_number
end

app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :units
  	attr_accessible :first_name, :last_name, :address, :phone_number, :email, :rfc
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :beginning_date, :diesel_total, :duration, :end_date, :file_name, :ledger_account, :period_number, :status, :total
  has_many :shifts
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  attr_accessible :day, :partner_earnings, :period_id, :period_id, :shift_total, :shift_type
  belongs_to :period
  has_many :bus_entries
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :number, :partner_id
  belongs_to :partner
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :name, :email, :password, :password_confirmation, :login, :crypted_password, :password_salt, :persistence_token, :single_access_token, :perishable_token, :login_count, :failed_login_count, :last_request_at, :current_login_at, :last_login_at, :current_login_ip, :last_login_ip
  acts_as_authentic do |c|
  	c.login_field = 'email'
  end # block optional
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/bus_entries_controller.rb
class BusEntriesController < ApplicationController
  # GET /bus_entries
  # GET /bus_entries.json
  def index
    @bus_entries = BusEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bus_entries }
    end
  end

  # GET /bus_entries/1
  # GET /bus_entries/1.json
  def show
    @bus_entry = BusEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bus_entry }
    end
  end

  # GET /bus_entries/new
  # GET /bus_entries/new.json
  def new
    @bus_entry = BusEntry.new
    @fares = Fare.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bus_entry }
    end
  end

  # GET /bus_entries/1/edit
  def edit
    @bus_entry = BusEntry.find(params[:id])
  end

  # POST /bus_entries
  # POST /bus_entries.json
  def create
    @bus_entry = BusEntry.new(params[:bus_entry])

    respond_to do |format|
      if @bus_entry.save
        format.html { redirect_to @bus_entry, notice: 'Bus entry was successfully created.' }
        format.json { render json: @bus_entry, status: :created, location: @bus_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @bus_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bus_entries/1
  # PUT /bus_entries/1.json
  def update
    @bus_entry = BusEntry.find(params[:id])

    respond_to do |format|
      if @bus_entry.update_attributes(params[:bus_entry])
        format.html { redirect_to @bus_entry, notice: 'Bus entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bus_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_entries/1
  # DELETE /bus_entries/1.json
  def destroy
    @bus_entry = BusEntry.find(params[:id])
    @bus_entry.destroy

    respond_to do |format|
      format.html { redirect_to bus_entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  # GET /fares
  # GET /fares.json
  def index
    @fares = Fare.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fares }
    end
  end

  # GET /fares/1
  # GET /fares/1.json
  def show
    @fare = Fare.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/new
  # GET /fares/new.json
  def new
    @fare = Fare.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/1/edit
  def edit
    @fare = Fare.find(params[:id])
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(params[:fare])

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render json: @fare, status: :created, location: @fare }
      else
        format.html { render action: "new" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fares/1
  # PUT /fares/1.json
  def update
    @fare = Fare.find(params[:id])

    respond_to do |format|
      if @fare.update_attributes(params[:fare])
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare = Fare.find(params[:id])
    @fare.destroy

    respond_to do |format|
      format.html { redirect_to fares_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def spanish_month(month)
  	mes = case month
  		when 1 then 'Ene'
  		when 2 then 'Feb'
  		when 3 then 'Mar'
  		when 4 then 'Abr'
  		when 5 then 'May'
  		when 6 then 'Jun'
  		when 7 then 'Jul'
  		when 8 then 'Ago'
  		when 9 then 'Sep'
  		when 10 then 'Oct'
  		when 11 then 'Nov'
  		when 12 then 'Dic'
  		else 'No es un mes'
  	end
  	mes
  end
end

app/helpers/bus_entries_helper.rb
module BusEntriesHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/bus_entries/_form.html.erb
<%= form_for @bus_entry, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :unit_id, 'ID de unidad', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :unit_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :operator_id, 'ID de operador', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :operator_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shift_id, 'ID de turno', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :shift_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :laps, 'Vueltas', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :laps, :class => 'number_field', :value=>0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :average_time, 'Tiempo de recorrido', :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :average_time, :class => 'time_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :preferent_tickets, 'Boletos preferentes', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :preferent_tickets, :class => 'number_field', :value=>0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :adult_tickets, 'Boletos adultos', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :adult_tickets, :class => 'number_field', :value=>0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :feria_tickets, 'Boletos tarjeta feria', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :feria_tickets, :class => 'text_field', :value=>0 %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :feria_total_income, 'Total tarjeta feria', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :feria_total_income, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :current_preferent_fare, 'Tarifa de boletos preferntes', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_preferent_fare, :class => 'text_field', :value=>@fares[0].price %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_adult_fare, 'Tarifa de boletos adultos', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_adult_fare, :class => 'text_field', :value=>@fares[1].price  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_feria_fare, 'Tarifa de tarjeta feria', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_feria_fare, :class => 'text_field', :value=>@fares[2].price  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total_tickets, 'Boletos totales', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :total_tickets, :class => 'number_field', :value=>0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total_income, 'Efectivo total', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_income, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :average_income, 'Tiempo total', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :average_income, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :worked_hours, 'Horas trabajadas', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :worked_hours, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :extra_hours, 'Horas extra', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :extra_hours, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :operator_salary, 'Salario', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :operator_salary, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :diesel_liters, 'Litros de diésel', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :diesel_liters, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :diesel_price, 'Precio de diésel', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :diesel_price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :unit_expenses, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unit_expenses, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :other_expenses, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :other_expenses, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :other_expenses_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :other_expenses_description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Agregar', :class => 'btn btn-default btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bus_entries_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/bus_entries/edit.html.erb
<%- model_class = BusEntry -%>
<div class="page-header">
  <h1>Editar entradas de cami&oacute;n </h1>
</div>
<%= render :partial => 'form' %>

app/views/bus_entries/index.html.erb
<%- model_class = BusEntry -%>
<div class="page-header">
  <h1>Entradas de cami&oacute;n</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:unit_id) %></th>
      <th><%= model_class.human_attribute_name(:operator_id) %></th>
      <th><%= model_class.human_attribute_name(:shift_id) %></th>
      <th><%= model_class.human_attribute_name(:laps) %></th>
      <th><%= model_class.human_attribute_name(:average_time) %></th>
      <th><%= model_class.human_attribute_name(:preferent_tickets) %></th>
      <th><%= model_class.human_attribute_name(:adult_tickets) %></th>
      <th><%= model_class.human_attribute_name(:feria_total_income) %></th>
      <th><%= model_class.human_attribute_name(:feria_tickets) %></th>
      <th><%= model_class.human_attribute_name(:current_preferent_fare) %></th>
      <th><%= model_class.human_attribute_name(:current_adult_fare) %></th>
      <th><%= model_class.human_attribute_name(:current_feria_fare) %></th>
      <th><%= model_class.human_attribute_name(:total_tickets) %></th>
      <th><%= model_class.human_attribute_name(:total_income) %></th>
      <th><%= model_class.human_attribute_name(:average_income) %></th>
      <th><%= model_class.human_attribute_name(:worked_hours) %></th>
      <th><%= model_class.human_attribute_name(:extra_hours) %></th>
      <th><%= model_class.human_attribute_name(:operator_salary) %></th>
      <th><%= model_class.human_attribute_name(:diesel_liters) %></th>
      <th><%= model_class.human_attribute_name(:diesel_price) %></th>
      <th><%= model_class.human_attribute_name(:unit_expenses) %></th>
      <th><%= model_class.human_attribute_name(:other_expenses) %></th>
      <th><%= model_class.human_attribute_name(:other_expenses_description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bus_entries.each do |bus_entry| %>
      <tr>
        <td><%= link_to bus_entry.id, bus_entry_path(bus_entry) %></td>
        <td><%= bus_entry.unit_id %></td>
        <td><%= bus_entry.operator_id %></td>
        <td><%= bus_entry.shift_id %></td>
        <td><%= bus_entry.laps %></td>
        <td><%= bus_entry.average_time %></td>
        <td><%= bus_entry.preferent_tickets %></td>
        <td><%= bus_entry.adult_tickets %></td>
        <td><%= bus_entry.feria_total_income %></td>
        <td><%= bus_entry.feria_tickets %></td>
        <td><%= bus_entry.current_preferent_fare %></td>
        <td><%= bus_entry.current_adult_fare %></td>
        <td><%= bus_entry.current_feria_fare %></td>
        <td><%= bus_entry.total_tickets %></td>
        <td><%= bus_entry.total_income %></td>
        <td><%= bus_entry.average_income %></td>
        <td><%= bus_entry.worked_hours %></td>
        <td><%= bus_entry.extra_hours %></td>
        <td><%= bus_entry.operator_salary %></td>
        <td><%= bus_entry.diesel_liters %></td>
        <td><%= bus_entry.diesel_price %></td>
        <td><%= bus_entry.unit_expenses %></td>
        <td><%= bus_entry.other_expenses %></td>
        <td><%= bus_entry.other_expenses_description %></td>
        <td><%=l bus_entry.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bus_entry_path(bus_entry), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bus_entry_path(bus_entry),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-default btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bus_entry_path,
            :class => 'btn btn-default btn-primary' %>

app/views/bus_entries/new.html.erb
<%- model_class = BusEntry -%>
<div class="page-header">
  <h1> Nueva entrada </h1>
</div>
<%= render :partial => 'form' %>

app/views/bus_entries/show.html.erb
<%- model_class = BusEntry -%>
<div class="page-header">
  <h1> Entradas de camiones </h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:unit_id) %>:</strong></dt>
  <dd><%= @bus_entry.unit_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operator_id) %>:</strong></dt>
  <dd><%= @bus_entry.operator_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shift_id) %>:</strong></dt>
  <dd><%= @bus_entry.shift_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:laps) %>:</strong></dt>
  <dd><%= @bus_entry.laps %></dd>
  <dt><strong><%= model_class.human_attribute_name(:average_time) %>:</strong></dt>
  <dd><%= @bus_entry.average_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preferent_tickets) %>:</strong></dt>
  <dd><%= @bus_entry.preferent_tickets %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adult_tickets) %>:</strong></dt>
  <dd><%= @bus_entry.adult_tickets %></dd>
  <dt><strong><%= model_class.human_attribute_name(:feria_total_income) %>:</strong></dt>
  <dd><%= @bus_entry.feria_total_income %></dd>
  <dt><strong><%= model_class.human_attribute_name(:feria_tickets) %>:</strong></dt>
  <dd><%= @bus_entry.feria_tickets %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_preferent_fare) %>:</strong></dt>
  <dd><%= @bus_entry.current_preferent_fare %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_adult_fare) %>:</strong></dt>
  <dd><%= @bus_entry.current_adult_fare %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_feria_fare) %>:</strong></dt>
  <dd><%= @bus_entry.current_feria_fare %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_tickets) %>:</strong></dt>
  <dd><%= @bus_entry.total_tickets %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_income) %>:</strong></dt>
  <dd><%= @bus_entry.total_income %></dd>
  <dt><strong><%= model_class.human_attribute_name(:average_income) %>:</strong></dt>
  <dd><%= @bus_entry.average_income %></dd>
  <dt><strong><%= model_class.human_attribute_name(:worked_hours) %>:</strong></dt>
  <dd><%= @bus_entry.worked_hours %></dd>
  <dt><strong><%= model_class.human_attribute_name(:extra_hours) %>:</strong></dt>
  <dd><%= @bus_entry.extra_hours %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operator_salary) %>:</strong></dt>
  <dd><%= @bus_entry.operator_salary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diesel_liters) %>:</strong></dt>
  <dd><%= @bus_entry.diesel_liters %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diesel_price) %>:</strong></dt>
  <dd><%= @bus_entry.diesel_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_expenses) %>:</strong></dt>
  <dd><%= @bus_entry.unit_expenses %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other_expenses) %>:</strong></dt>
  <dd><%= @bus_entry.other_expenses %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other_expenses_description) %>:</strong></dt>
  <dd><%= @bus_entry.other_expenses_description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bus_entries_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bus_entry_path(@bus_entry), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bus_entry_path(@bus_entry),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-default btn-danger' %>
</div>