config/routes.rb
Rutas::Application.routes.draw do
  resources :bus_entries
  resources :fares
  resources :bus_entry_vouchers
  resources :vouchers
  resources :shifts
  resources :periods
  resources :operators
  resources :units
  resources :partners
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup

  root :to => 'users#new'

end

app/models/bus_entry.rb
class BusEntry < ActiveRecord::Base
  attr_accessible :adult_tickets, :average_income, :average_time, :current_adult_fare, :current_feria_fare, :current_preferent_fare, :diesel_liters, :diesel_price, :extra_hours, :feria_tickets, :feria_total_income, :laps, :operator_id, :operator_salary, :other_expenses, :other_expenses_description, :preferent_tickets, :shift_id, :total_income, :total_tickets, :unit_expenses, :unit_id, :worked_hours
  belongs_to :shift
end

app/models/bus_entry_voucher.rb
class BusEntryVoucher < ActiveRecord::Base
  attr_accessible :amount, :bus_entry_id, :voucher_id
end

app/models/fare.rb
class Fare < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :address, :cellphone_number, :email, :employee_number, :first_name, :last_name, :phone_number
end

app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :units
  	attr_accessible :first_name, :last_name, :address, :phone_number, :email, :rfc
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :beginning_date, :diesel_total, :duration, :end_date, :file_name, :ledger_account, :period_number, :status, :total
  has_many :shifts
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  attr_accessible :day, :partner_earnings, :period_id, :period_id, :shift_total, :shift_type
  belongs_to :period
  has_many :bus_entries
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :number, :partner_id
  belongs_to :partner
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :name, :email, :password, :password_confirmation, :login, :crypted_password, :password_salt, :persistence_token, :single_access_token, :perishable_token, :login_count, :failed_login_count, :last_request_at, :current_login_at, :last_login_at, :current_login_ip, :last_login_ip
  acts_as_authentic do |c|
  	c.login_field = 'email'
  end # block optional
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  # GET /fares
  # GET /fares.json
  def index
    @fares = Fare.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fares }
    end
  end

  # GET /fares/1
  # GET /fares/1.json
  def show
    @fare = Fare.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/new
  # GET /fares/new.json
  def new
    @fare = Fare.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/1/edit
  def edit
    @fare = Fare.find(params[:id])
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(params[:fare])

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render json: @fare, status: :created, location: @fare }
      else
        format.html { render action: "new" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fares/1
  # PUT /fares/1.json
  def update
    @fare = Fare.find(params[:id])

    respond_to do |format|
      if @fare.update_attributes(params[:fare])
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare = Fare.find(params[:id])
    @fare.destroy

    respond_to do |format|
      format.html { redirect_to fares_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shifts }
    end
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
    @shift = Shift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shift }
    end
  end

  # GET /shifts/new
  # GET /shifts/new.json
  def new
    @shift = Shift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shift }
    end
  end

  # GET /shifts/1/edit
  def edit
    @shift = Shift.find(params[:id])
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(params[:shift])

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render json: @shift, status: :created, location: @shift }
      else
        format.html { render action: "new" }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shifts/1
  # PUT /shifts/1.json
  def update
    @shift = Shift.find(params[:id])

    respond_to do |format|
      if @shift.update_attributes(params[:shift])
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to shifts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def spanish_month(month)
  	mes = case month
  		when 1 then 'Ene'
  		when 2 then 'Feb'
  		when 3 then 'Mar'
  		when 4 then 'Abr'
  		when 5 then 'May'
  		when 6 then 'Jun'
  		when 7 then 'Jul'
  		when 8 then 'Ago'
  		when 9 then 'Sep'
  		when 10 then 'Oct'
  		when 11 then 'Nov'
  		when 12 then 'Dic'
  		else 'No es un mes'
  	end
  	mes
  end
end

app/helpers/bus_entries_helper.rb
module BusEntriesHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/shifts/_form.html.erb
<%= form_for @shift, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :period_id, 'ID', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :period_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shift_type, 'Tipo', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :shift_type, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shift_total, 'Turno total', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :shift_total, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :partner_earnings, 'Ganancias', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :partner_earnings, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :day, 'Día', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :day, :class => 'date_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Crear', :class => 'btn btn-default btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shifts_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<%- model_class = Shift -%>
<div class="page-header">
  <h1> Editar turnos </h1>
</div>
<%= render :partial => 'form' %>

app/views/shifts/index.html.erb
<%- model_class = Shift -%>
<div class="page-header">
  <h1> Turnos </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th> ID </th>
      <th> Per&iacute;odo </th>
      <th> Tipo </th>
      <th> Turno total </th>
      <th> Ganancias</th>
      <th> D&iacute;a </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= link_to shift.id, shift_path(shift) %></td>
        <td><%= shift.period_id %></td>
        <td><%= shift.shift_type %></td>
        <td><%= shift.shift_total %></td>
        <td><%= shift.partner_earnings %></td>
        <td><%= shift.day %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shift_path(shift), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shift_path(shift),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-default btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shift_path,
            :class => 'btn btn-default btn-primary' %>

app/views/shifts/new.html.erb
<%- model_class = Shift -%>
<div class="page-header">
  <h1> Nuevo turno </h1>
</div>
<%= render :partial => 'form' %>

app/views/shifts/show.html.erb
<%- model_class = Shift -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:period_id) %>:</strong></dt>
  <dd><%= @shift.period_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shift_type) %>:</strong></dt>
  <dd><%= @shift.shift_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shift_total) %>:</strong></dt>
  <dd><%= @shift.shift_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:partner_earnings) %>:</strong></dt>
  <dd><%= @shift.partner_earnings %></dd>
  <dt><strong><%= model_class.human_attribute_name(:day) %>:</strong></dt>
  <dd><%= @shift.day %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              shifts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shift_path(@shift), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shift_path(@shift),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarlo permanentemente de la base de datos?')) },
              :class => 'btn btn-default btn-danger' %>
</div>