config/routes.rb
Rutas::Application.routes.draw do
  resources :bus_entries
  resources :fares
  resources :bus_entry_vouchers
  resources :vouchers
  resources :shifts
  resources :periods
  resources :operators
  resources :units
  resources :partners
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup

  root :to => 'users#new'

end

app/models/bus_entry.rb
class BusEntry < ActiveRecord::Base
  attr_accessible :adult_tickets, :average_income, :average_time, :current_adult_fare, :current_feria_fare, :current_preferent_fare, :diesel_liters, :diesel_price, :extra_hours, :feria_tickets, :feria_total_income, :laps, :operator_id, :operator_salary, :other_expenses, :other_expenses_description, :preferent_tickets, :shift_id, :total_income, :total_tickets, :unit_expenses, :unit_id, :worked_hours
  belongs_to :shift
end

app/models/bus_entry_voucher.rb
class BusEntryVoucher < ActiveRecord::Base
  attr_accessible :amount, :bus_entry_id, :voucher_id
end

app/models/fare.rb
class Fare < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  attr_accessible :address, :cellphone_number, :email, :employee_number, :first_name, :last_name, :phone_number
end

app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :units
  	attr_accessible :first_name, :last_name, :address, :phone_number, :email, :rfc
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :beginning_date, :diesel_total, :duration, :end_date, :file_name, :ledger_account, :period_number, :status, :total
  has_many :shifts
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  attr_accessible :day, :partner_earnings, :period_id, :period_id, :shift_total, :shift_type
  belongs_to :period
  has_many :bus_entries
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :number, :partner_id
  belongs_to :partner
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :name, :email, :password, :password_confirmation, :login, :crypted_password, :password_salt, :persistence_token, :single_access_token, :perishable_token, :login_count, :failed_login_count, :last_request_at, :current_login_at, :last_login_at, :current_login_ip, :last_login_ip
  acts_as_authentic do |c|
  	c.login_field = 'email'
  end # block optional
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  # GET /fares
  # GET /fares.json
  def index
    @fares = Fare.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fares }
    end
  end

  # GET /fares/1
  # GET /fares/1.json
  def show
    @fare = Fare.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/new
  # GET /fares/new.json
  def new
    @fare = Fare.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fare }
    end
  end

  # GET /fares/1/edit
  def edit
    @fare = Fare.find(params[:id])
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(params[:fare])

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render json: @fare, status: :created, location: @fare }
      else
        format.html { render action: "new" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fares/1
  # PUT /fares/1.json
  def update
    @fare = Fare.find(params[:id])

    respond_to do |format|
      if @fare.update_attributes(params[:fare])
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare = Fare.find(params[:id])
    @fare.destroy

    respond_to do |format|
      format.html { redirect_to fares_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unidad agregada correctamente.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unidad actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def spanish_month(month)
  	mes = case month
  		when 1 then 'Ene'
  		when 2 then 'Feb'
  		when 3 then 'Mar'
  		when 4 then 'Abr'
  		when 5 then 'May'
  		when 6 then 'Jun'
  		when 7 then 'Jul'
  		when 8 then 'Ago'
  		when 9 then 'Sep'
  		when 10 then 'Oct'
  		when 11 then 'Nov'
  		when 12 then 'Dic'
  		else 'No es un mes'
  	end
  	mes
  end
end

app/helpers/bus_entries_helper.rb
module BusEntriesHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/fares/_form.html.erb
<%= form_for @fare, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, 'Tipo de tarifa', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, 'Precio', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Crear', :class => 'btn btn-default btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fares_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/fares/edit.html.erb
<%- model_class = Fare -%>
<div class="page-header">
  <h1>Editar tarifa</h1>
</div>
<%= render :partial => 'form' %>

app/views/fares/index.html.erb
<%- model_class = Fare -%>
<div class="page-header">
  <h1> Tarifas </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th> Tipo de tarifa </th>
      <th> Precio </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fares.each do |fare| %>
      <tr>
        <td><%= fare.name %></td>
        <td><%= fare.price %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_fare_path(fare), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fare_path(fare),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarlo por permanentemente de la base de datos?')) },
                      :class => 'btn btn-default btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fare_path,
            :class => 'btn btn-default btn-primary' %>

app/views/fares/new.html.erb
<%- model_class = Fare -%>
<div class="page-header">
  <h1> Nueva tarifa </h1>
</div>
<%= render :partial => 'form' %>

app/views/fares/show.html.erb
<%- model_class = Fare -%>
<div class="page-header">
  <h1> Tarifas </h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @fare.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @fare.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fares_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fare_path(@fare), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fare_path(@fare),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarla permanentemente de la base de datos?')) },
              :class => 'btn btn-default btn-danger' %>
</div>

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, 'Número de unidad', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :partner_id, 'Socio propietario', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :partner_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Agregar', :class => 'btn btn-default btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                units_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1> Editar unidad </h1>
</div>
<%= render :partial => 'form' %>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1> Unidades </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th> Unidad </th>
      <th> Socio </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.id, unit_path(unit) %></td>
        <td><%= unit.partner_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarlo permanentemente de la base de datos?')) },
                      :class => 'btn btn-default btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_path,
            :class => 'btn btn-default btn-primary' %>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1> Nueva Unidad </h1>
</div>
<%= render :partial => 'form' %>

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @unit.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @unit.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:partner_id) %>:</strong></dt>
  <dd><%= @unit.partner_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro que desea eliminarlo permanentemente de la base de datos?')) },
              :class => 'btn btn-default btn-danger' %>
</div>